// Auto-generated list of all available icons
// Generated: 2025-11-03
// Total icons: 272

const ALL_AVAILABLE_ICONS = [
    { file: 'BOCOF001.ICO', name: 'Book' },
    { file: 'CALC001.ICO', name: 'Calculator' },
    { file: 'CARDF001.ICO', name: 'Card File' },
    { file: 'CardFile.ICO', name: 'Card File' },
    { file: 'CHARM001.ICO', name: 'Character Map' },
    { file: 'CLIPB001.ICO', name: 'Clipboard 1' },
    { file: 'CLIPB002.ICO', name: 'Clipboard 2' },
    { file: 'CLIPB003.ICO', name: 'Clipboard 3' },
    { file: 'CLIPB004.ICO', name: 'Clipboard 4' },
    { file: 'CLIPB005.ICO', name: 'Clipboard 5' },
    { file: 'CLIPB006.ICO', name: 'Clipboard 6' },
    { file: 'CLOCK001.ICO', name: 'Clock' },
    { file: 'CMC001.ICO', name: 'CMC 1' },
    { file: 'CMC002.ICO', name: 'CMC 2' },
    { file: 'CMC003.ICO', name: 'CMC 3' },
    { file: 'COMMC001.ICO', name: 'Communication' },
    { file: 'COMMD001.ICO', name: 'Command 1' },
    { file: 'COMMD002.ICO', name: 'Command 2' },
    { file: 'CONTR001.ICO', name: 'Control Panel' },
    { file: 'Door.ICO', name: 'Door' },
    { file: 'FAXMG001.ICO', name: 'Fax Manager' },
    { file: 'FAXOP001.ICO', name: 'Fax Options' },
    { file: 'FAXVI001.ICO', name: 'Fax Viewer' },
    { file: 'hearts.ICO', name: 'Hearts' },
    { file: 'Ideas.ICO', name: 'Ideas' },
    { file: 'KEYVI001.ICO', name: 'Keyboard' },
    { file: 'LifeAdmin.ICO', name: 'Life Admin' },
    { file: 'Living.ICO', name: 'Living' },
    { file: 'LOGON001.ICO', name: 'Logon' },
    { file: 'MAILS001.ICO', name: 'Mail 1' },
    { file: 'MAILS002.ICO', name: 'Mail 2' },
    { file: 'MAILS003.ICO', name: 'Mail 3' },
    { file: 'MAILS004.ICO', name: 'Mail 4' },
    { file: 'MAILS005.ICO', name: 'Mail 5' },
    { file: 'MAPI001.ICO', name: 'MAPI 1' },
    { file: 'MAPI002.ICO', name: 'MAPI 2' },
    { file: 'MAPI003.ICO', name: 'MAPI 3' },
    { file: 'MORIC001.ICO', name: 'Moricons 1' },
    { file: 'MORIC002.ICO', name: 'Moricons 2' },
    { file: 'MORIC003.ICO', name: 'Moricons 3' },
    { file: 'MORIC004.ICO', name: 'Moricons 4' },
    { file: 'MORIC005.ICO', name: 'Moricons 5' },
    { file: 'MORIC006.ICO', name: 'Moricons 6' },
    { file: 'MORIC007.ICO', name: 'Moricons 7' },
    { file: 'MORIC008.ICO', name: 'Moricons 8' },
    { file: 'MORIC009.ICO', name: 'Moricons 9' },
    { file: 'MORIC010.ICO', name: 'Moricons 10' },
    { file: 'MORIC011.ICO', name: 'Moricons 11' },
    { file: 'MORIC012.ICO', name: 'Moricons 12' },
    { file: 'MORIC013.ICO', name: 'Moricons 13' },
    { file: 'MORIC014.ICO', name: 'Moricons 14' },
    { file: 'MORIC015.ICO', name: 'Moricons 15' },
    { file: 'MORIC016.ICO', name: 'Moricons 16' },
    { file: 'MORIC017.ICO', name: 'Moricons 17' },
    { file: 'MORIC018.ICO', name: 'Moricons 18' },
    { file: 'MORIC019.ICO', name: 'Moricons 19' },
    { file: 'MORIC020.ICO', name: 'Moricons 20' },
    { file: 'MORIC021.ICO', name: 'Moricons 21' },
    { file: 'MORIC022.ICO', name: 'Moricons 22' },
    { file: 'MORIC023.ICO', name: 'Moricons 23' },
    { file: 'MORIC024.ICO', name: 'Moricons 24' },
    { file: 'MORIC025.ICO', name: 'Moricons 25' },
    { file: 'MORIC026.ICO', name: 'Moricons 26' },
    { file: 'MORIC027.ICO', name: 'Moricons 27' },
    { file: 'MORIC028.ICO', name: 'Moricons 28' },
    { file: 'MORIC029.ICO', name: 'Moricons 29' },
    { file: 'MORIC030.ICO', name: 'Moricons 30' },
    { file: 'MORIC031.ICO', name: 'Moricons 31' },
    { file: 'MORIC032.ICO', name: 'Moricons 32' },
    { file: 'MORIC033.ICO', name: 'Moricons 33' },
    { file: 'MORIC034.ICO', name: 'Moricons 34' },
    { file: 'MORIC035.ICO', name: 'Moricons 35' },
    { file: 'MORIC036.ICO', name: 'Moricons 36' },
    { file: 'MORIC037.ICO', name: 'Moricons 37' },
    { file: 'MORIC038.ICO', name: 'Moricons 38' },
    { file: 'MORIC039.ICO', name: 'Moricons 39' },
    { file: 'MORIC040.ICO', name: 'Moricons 40' },
    { file: 'MORIC041.ICO', name: 'Moricons 41' },
    { file: 'MORIC042.ICO', name: 'Moricons 42' },
    { file: 'MORIC043.ICO', name: 'Moricons 43' },
    { file: 'MORIC044.ICO', name: 'Moricons 44' },
    { file: 'MORIC045.ICO', name: 'Moricons 45' },
    { file: 'MORIC046.ICO', name: 'Moricons 46' },
    { file: 'MORIC047.ICO', name: 'Moricons 47' },
    { file: 'MORIC048.ICO', name: 'Moricons 48' },
    { file: 'MORIC049.ICO', name: 'Moricons 49' },
    { file: 'MORIC050.ICO', name: 'Moricons 50' },
    { file: 'MORIC051.ICO', name: 'Moricons 51' },
    { file: 'MORIC052.ICO', name: 'Moricons 52' },
    { file: 'MORIC053.ICO', name: 'Moricons 53' },
    { file: 'MORIC054.ICO', name: 'Moricons 54' },
    { file: 'MORIC055.ICO', name: 'Moricons 55' },
    { file: 'MORIC056.ICO', name: 'Moricons 56' },
    { file: 'MORIC057.ICO', name: 'Moricons 57' },
    { file: 'MORIC058.ICO', name: 'Moricons 58' },
    { file: 'MORIC059.ICO', name: 'Moricons 59' },
    { file: 'MORIC060.ICO', name: 'Moricons 60' },
    { file: 'MORIC061.ICO', name: 'Moricons 61' },
    { file: 'MORIC062.ICO', name: 'Moricons 62' },
    { file: 'MORIC063.ICO', name: 'Moricons 63' },
    { file: 'MORIC064.ICO', name: 'Moricons 64' },
    { file: 'MORIC065.ICO', name: 'Moricons 65' },
    { file: 'MORIC066.ICO', name: 'Moricons 66' },
    { file: 'MORIC067.ICO', name: 'Moricons 67' },
    { file: 'MORIC068.ICO', name: 'Moricons 68' },
    { file: 'MORIC069.ICO', name: 'Moricons 69' },
    { file: 'MORIC070.ICO', name: 'Moricons 70' },
    { file: 'MORIC071.ICO', name: 'Moricons 71' },
    { file: 'MORIC072.ICO', name: 'Moricons 72' },
    { file: 'MORIC073.ICO', name: 'Moricons 73' },
    { file: 'MORIC074.ICO', name: 'Moricons 74' },
    { file: 'MORIC075.ICO', name: 'Moricons 75' },
    { file: 'MORIC076.ICO', name: 'Moricons 76' },
    { file: 'MORIC077.ICO', name: 'Moricons 77' },
    { file: 'MORIC078.ICO', name: 'Moricons 78' },
    { file: 'MORIC079.ICO', name: 'Moricons 79' },
    { file: 'MORIC080.ICO', name: 'Moricons 80' },
    { file: 'MORIC081.ICO', name: 'Moricons 81' },
    { file: 'MORIC082.ICO', name: 'Moricons 82' },
    { file: 'MORIC083.ICO', name: 'Moricons 83' },
    { file: 'MORIC084.ICO', name: 'Moricons 84' },
    { file: 'MORIC085.ICO', name: 'Moricons 85' },
    { file: 'MORIC086.ICO', name: 'Moricons 86' },
    { file: 'MORIC087.ICO', name: 'Moricons 87' },
    { file: 'MORIC088.ICO', name: 'Moricons 88' },
    { file: 'MORIC089.ICO', name: 'Moricons 89' },
    { file: 'MORIC090.ICO', name: 'Moricons 90' },
    { file: 'MORIC091.ICO', name: 'Moricons 91' },
    { file: 'MORIC092.ICO', name: 'Moricons 92' },
    { file: 'MORIC093.ICO', name: 'Moricons 93' },
    { file: 'MORIC094.ICO', name: 'Moricons 94' },
    { file: 'MORIC095.ICO', name: 'Moricons 95' },
    { file: 'MORIC096.ICO', name: 'Moricons 96' },
    { file: 'MORIC097.ICO', name: 'Moricons 97' },
    { file: 'MORIC098.ICO', name: 'Moricons 98' },
    { file: 'MORIC099.ICO', name: 'Moricons 99' },
    { file: 'MORIC100.ICO', name: 'Moricons 100' },
    { file: 'MORIC101.ICO', name: 'Moricons 101' },
    { file: 'MORIC102.ICO', name: 'Moricons 102' },
    { file: 'MORIC103.ICO', name: 'Moricons 103' },
    { file: 'MORIC104.ICO', name: 'Moricons 104' },
    { file: 'MORIC105.ICO', name: 'Moricons 105' },
    { file: 'MORIC106.ICO', name: 'Moricons 106' },
    { file: 'MPLAY001.ICO', name: 'Media Player' },
    { file: 'MSHEA001.ICO', name: 'MS Hearts' },
    { file: 'MSMAI001.ICO', name: 'Mail 1' },
    { file: 'MSMAI002.ICO', name: 'Mail 2' },
    { file: 'MSMAI003.ICO', name: 'Mail 3' },
    { file: 'MSMAI004.ICO', name: 'Mail 4' },
    { file: 'MSMAI005.ICO', name: 'Mail 5' },
    { file: 'MSMAI006.ICO', name: 'Mail 6' },
    { file: 'MSMAI007.ICO', name: 'Mail 7' },
    { file: 'MSMAI008.ICO', name: 'Mail 8' },
    { file: 'MSMAI009.ICO', name: 'Mail 9' },
    { file: 'MSMAI010.ICO', name: 'Mail 10' },
    { file: 'MSMAI011.ICO', name: 'Mail 11' },
    { file: 'MSMAI012.ICO', name: 'Mail 12' },
    { file: 'MSREM001.ICO', name: 'Reminder' },
    { file: 'NETWA001.ICO', name: 'Network 1' },
    { file: 'NETWA002.ICO', name: 'Network 2' },
    { file: 'NOTEP001.ICO', name: 'Notepad' },
    { file: 'OLE2001.ICO', name: 'OLE' },
    { file: 'PACKA001.ICO', name: 'Package' },
    { file: 'PaintBrush.ICO', name: 'Paint Brush' },
    { file: 'PBRUS001.ICO', name: 'Paint Brush' },
    { file: 'Photography.ICO', name: 'Photography' },
    { file: 'PIFED001.ICO', name: 'PIF Editor' },
    { file: 'PRINT001.ICO', name: 'Printer' },
    { file: 'PROGM001.ICO', name: 'Program 1' },
    { file: 'PROGM002.ICO', name: 'Program 2' },
    { file: 'PROGM003.ICO', name: 'Program 3' },
    { file: 'PROGM004.ICO', name: 'Program 4' },
    { file: 'PROGM005.ICO', name: 'Program 5' },
    { file: 'PROGM006.ICO', name: 'Program 6' },
    { file: 'PROGM007.ICO', name: 'Program 7' },
    { file: 'PROGM008.ICO', name: 'Program 8' },
    { file: 'PROGM009.ICO', name: 'Program 9' },
    { file: 'PROGM010.ICO', name: 'Program 10' },
    { file: 'PROGM011.ICO', name: 'Program 11' },
    { file: 'PROGM012.ICO', name: 'Program 12' },
    { file: 'PROGM013.ICO', name: 'Program 13' },
    { file: 'PROGM014.ICO', name: 'Program 14' },
    { file: 'PROGM015.ICO', name: 'Program 15' },
    { file: 'PROGM016.ICO', name: 'Program 16' },
    { file: 'PROGM017.ICO', name: 'Program 17' },
    { file: 'PROGM018.ICO', name: 'Program 18' },
    { file: 'PROGM019.ICO', name: 'Program 19' },
    { file: 'PROGM020.ICO', name: 'Program 20' },
    { file: 'PROGM021.ICO', name: 'Program 21' },
    { file: 'PROGM022.ICO', name: 'Program 22' },
    { file: 'PROGM023.ICO', name: 'Program 23' },
    { file: 'PROGM024.ICO', name: 'Program 24' },
    { file: 'PROGM025.ICO', name: 'Program 25' },
    { file: 'PROGM026.ICO', name: 'Program 26' },
    { file: 'PROGM027.ICO', name: 'Program 27' },
    { file: 'PROGM028.ICO', name: 'Program 28' },
    { file: 'PROGM029.ICO', name: 'Program 29' },
    { file: 'PROGM030.ICO', name: 'Program 30' },
    { file: 'PROGM031.ICO', name: 'Program 31' },
    { file: 'PROGM032.ICO', name: 'Program 32' },
    { file: 'PROGM033.ICO', name: 'Program 33' },
    { file: 'PROGM034.ICO', name: 'Program 34' },
    { file: 'PROGM035.ICO', name: 'Program 35' },
    { file: 'PROGM036.ICO', name: 'Program 36' },
    { file: 'PROGM037.ICO', name: 'Program 37' },
    { file: 'PROGM038.ICO', name: 'Program 38' },
    { file: 'PROGM039.ICO', name: 'Program 39' },
    { file: 'PROGM040.ICO', name: 'Program 40' },
    { file: 'PROGM041.ICO', name: 'Program 41' },
    { file: 'PROGM042.ICO', name: 'Program 42' },
    { file: 'PROGM043.ICO', name: 'Program 43' },
    { file: 'PROGM044.ICO', name: 'Program 44' },
    { file: 'PROGM045.ICO', name: 'Program 45' },
    { file: 'PROGM046.ICO', name: 'Program 46' },
    { file: 'RASST001.ICO', name: 'Remote Access' },
    { file: 'RECOR001.ICO', name: 'Recorder' },
    { file: 'REGED001.ICO', name: 'Registry Editor' },
    { file: 'Relationships.ICO', name: 'Relationships' },
    { file: 'SCHDP001.ICO', name: 'Schedule 1' },
    { file: 'SCHDP002.ICO', name: 'Schedule 2' },
    { file: 'SCHDP003.ICO', name: 'Schedule 3' },
    { file: 'SCHDP004.ICO', name: 'Schedule 4' },
    { file: 'SCHDP005.ICO', name: 'Schedule 5' },
    { file: 'SCHDP006.ICO', name: 'Schedule 6' },
    { file: 'SCHDP007.ICO', name: 'Schedule 7' },
    { file: 'SCHDP008.ICO', name: 'Schedule 8' },
    { file: 'SIGVI001.ICO', name: 'Signature' },
    { file: 'SOL001.ICO', name: 'Solitaire' },
    { file: 'SOUND001.ICO', name: 'Sound' },
    { file: 'STORE001.ICO', name: 'Store' },
    { file: 'SYSED001.ICO', name: 'System Editor 1' },
    { file: 'SYSED002.ICO', name: 'System Editor 2' },
    { file: 'TERMI001.ICO', name: 'Terminal' },
    { file: 'UNIDR001.ICO', name: 'UniDriver 1' },
    { file: 'UNIDR002.ICO', name: 'UniDriver 2' },
    { file: 'UNIDR003.ICO', name: 'UniDriver 3' },
    { file: 'UNIDR004.ICO', name: 'UniDriver 4' },
    { file: 'UNIDR005.ICO', name: 'UniDriver 5' },
    { file: 'UNIDR006.ICO', name: 'UniDriver 6' },
    { file: 'UNIDR007.ICO', name: 'UniDriver 7' },
    { file: 'UNIDR008.ICO', name: 'UniDriver 8' },
    { file: 'UNINS001.ICO', name: 'Uninstall' },
    { file: 'UNWIS001.ICO', name: 'Unwise' },
    { file: 'USER001.ICO', name: 'User' },
    { file: 'VBRUN001.ICO', name: 'VB Runtime 1' },
    { file: 'VBRUN002.ICO', name: 'VB Runtime 2' },
    { file: 'VBRUN003.ICO', name: 'VB Runtime 3' },
    { file: 'VFORM001.ICO', name: 'VB Form 1' },
    { file: 'VFORM002.ICO', name: 'VB Form 2' },
    { file: 'VFORM003.ICO', name: 'VB Form 3' },
    { file: 'WFWSE001.ICO', name: 'WFW Setup 1' },
    { file: 'WFWSE002.ICO', name: 'WFW Setup 2' },
    { file: 'WFWSE003.ICO', name: 'WFW Setup 3' },
    { file: 'WFWSE004.ICO', name: 'WFW Setup 4' },
    { file: 'WFWSE005.ICO', name: 'WFW Setup 5' },
    { file: 'WFWSE006.ICO', name: 'WFW Setup 6' },
    { file: 'WFWSE007.ICO', name: 'WFW Setup 7' },
    { file: 'WINCH001.ICO', name: 'WinChat 1' },
    { file: 'WINCH002.ICO', name: 'WinChat 2' },
    { file: 'WINCH003.ICO', name: 'WinChat 3' },
    { file: 'WINFI001.ICO', name: 'File 1' },
    { file: 'WINFI002.ICO', name: 'File 2' },
    { file: 'WINFI003.ICO', name: 'File 3' },
    { file: 'WINFI004.ICO', name: 'File 4' },
    { file: 'WINHE001.ICO', name: 'Help' },
    { file: 'WINHL001.ICO', name: 'WinHelp 1' },
    { file: 'WINHL002.ICO', name: 'WinHelp 2' },
    { file: 'WINHL003.ICO', name: 'WinHelp 3' },
    { file: 'WINME001.ICO', name: 'WinMeter' },
    { file: 'WINMI001.ICO', name: 'Mines' },
    { file: 'WINPO001.ICO', name: 'WinPopup 1' },
    { file: 'WINPO002.ICO', name: 'WinPopup 2' },
    { file: 'WINPO003.ICO', name: 'WinPopup 3' },
    { file: 'WINSE001.ICO', name: 'Setup 1' },
    { file: 'WINSE002.ICO', name: 'Setup 2' },
    { file: 'WINSE003.ICO', name: 'Setup 3' },
    { file: 'WINSE004.ICO', name: 'Setup 4' },
    { file: 'WINSE005.ICO', name: 'Setup 5' },
    { file: 'WINTU001.ICO', name: 'Tutorial 1' },
    { file: 'WINTU002.ICO', name: 'Tutorial 2' },
    { file: 'WINTU003.ICO', name: 'Tutorial 3' },
    { file: 'WINTU004.ICO', name: 'Tutorial 4' },
    { file: 'WINTU005.ICO', name: 'Tutorial 5' },
    { file: 'WINTU006.ICO', name: 'Tutorial 6' },
    { file: 'WINTU007.ICO', name: 'Tutorial 7' },
    { file: 'WINVE001.ICO', name: 'Version' },
    { file: 'Work.ICO', name: 'Work' },
    { file: 'WRITE001.ICO', name: 'Write' },
    { file: 'YellowCircleBlackExclamtation.ICO', name: 'Warning' }
];

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = ALL_AVAILABLE_ICONS;
}
